export default {
    carbonEmission: {
        CUP_MINI: {singleUse: Math.floor(Math.random() * 50 + 50), multiUse: Math.floor(Math.random() * 30)},
        CUP_SMALL: {singleUse: Math.floor(Math.random() * 50 + 50), multiUse: Math.floor(Math.random() * 30)},
        CUP_MEDIUM: {singleUse: Math.floor(Math.random() * 50 + 50), multiUse: Math.floor(Math.random() * 30)},
        CUP_LARGE: {singleUse: Math.floor(Math.random() * 50 + 50), multiUse: Math.floor(Math.random() * 30)},
        PLATE_MINI: {singleUse: Math.floor(Math.random() * 50 + 50), multiUse: Math.floor(Math.random() * 30)},
        PLATE_SMALL: {singleUse: Math.floor(Math.random() * 50 + 50), multiUse: Math.floor(Math.random() * 30)},
        PLATE_MEDIUM: {singleUse: Math.floor(Math.random() * 50 + 50), multiUse: Math.floor(Math.random() * 30)},
        PLATE_LARGE: {singleUse: Math.floor(Math.random() * 50 + 50), multiUse: Math.floor(Math.random() * 30)},
        TUMBLR_SMALL: {singleUse: Math.floor(Math.random() * 50 + 50), multiUse: Math.floor(Math.random() * 30)},
        TUMBLR_LARGE: {singleUse: Math.floor(Math.random() * 50 + 50), multiUse: Math.floor(Math.random() * 30)},
        TRAY_SMALL: {singleUse: Math.floor(Math.random() * 50 + 50), multiUse: Math.floor(Math.random() * 30)},
        TRAY_LARGE: {singleUse: Math.floor(Math.random() * 50 + 50), multiUse: Math.floor(Math.random() * 30)},
        BOX_SMALL: {singleUse: Math.floor(Math.random() * 50 + 50), multiUse: Math.floor(Math.random() * 30)},
        BOX_MEDIUM: {singleUse: Math.floor(Math.random() * 50 + 50), multiUse: Math.floor(Math.random() * 30)},
        BOX_LARGE: {singleUse: Math.floor(Math.random() * 50 + 50), multiUse: Math.floor(Math.random() * 30)},
    },
    cost: {
        CUP_MINI: {singleUse: Math.floor(Math.random() * 50 + 50), multiUse: Math.floor(Math.random() * 30)},
        CUP_SMALL: {singleUse: Math.floor(Math.random() * 50 + 50), multiUse: Math.floor(Math.random() * 30)},
        CUP_MEDIUM: {singleUse: Math.floor(Math.random() * 50 + 50), multiUse: Math.floor(Math.random() * 30)},
        CUP_LARGE: {singleUse: Math.floor(Math.random() * 50 + 50), multiUse: Math.floor(Math.random() * 30)},
        PLATE_MINI: {singleUse: Math.floor(Math.random() * 50 + 50), multiUse: Math.floor(Math.random() * 30)},
        PLATE_SMALL: {singleUse: Math.floor(Math.random() * 50 + 50), multiUse: Math.floor(Math.random() * 30)},
        PLATE_MEDIUM: {singleUse: Math.floor(Math.random() * 50 + 50), multiUse: Math.floor(Math.random() * 30)},
        PLATE_LARGE: {singleUse: Math.floor(Math.random() * 50 + 50), multiUse: Math.floor(Math.random() * 30)},
        TUMBLR_SMALL: {singleUse: Math.floor(Math.random() * 50 + 50), multiUse: Math.floor(Math.random() * 30)},
        TUMBLR_LARGE: {singleUse: Math.floor(Math.random() * 50 + 50), multiUse: Math.floor(Math.random() * 30)},
        TRAY_SMALL: {singleUse: Math.floor(Math.random() * 50 + 50), multiUse: Math.floor(Math.random() * 30)},
        TRAY_LARGE: {singleUse: Math.floor(Math.random() * 50 + 50), multiUse: Math.floor(Math.random() * 30)},
        BOX_SMALL: {singleUse: Math.floor(Math.random() * 50 + 50), multiUse: Math.floor(Math.random() * 30)},
        BOX_MEDIUM: {singleUse: Math.floor(Math.random() * 50 + 50), multiUse: Math.floor(Math.random() * 30)},
        BOX_LARGE: {singleUse: Math.floor(Math.random() * 50 + 50), multiUse: Math.floor(Math.random() * 30)},
    },
    usage: {
        CUP_MINI: {use: Math.floor(Math.random() * 50 + 50), return: Math.floor(Math.random() * 30)},
        CUP_SMALL: {use: Math.floor(Math.random() * 50 + 50), return: Math.floor(Math.random() * 30)},
        CUP_MEDIUM: {use: Math.floor(Math.random() * 50 + 50), return: Math.floor(Math.random() * 30)},
        CUP_LARGE: {use: Math.floor(Math.random() * 50 + 50), return: Math.floor(Math.random() * 30)},
        PLATE_MINI: {use: Math.floor(Math.random() * 50 + 50), return: Math.floor(Math.random() * 30)},
        PLATE_SMALL: {use: Math.floor(Math.random() * 50 + 50), return: Math.floor(Math.random() * 30)},
        PLATE_MEDIUM: {use: Math.floor(Math.random() * 50 + 50), return: Math.floor(Math.random() * 30)},
        PLATE_LARGE: {use: Math.floor(Math.random() * 50 + 50), return: Math.floor(Math.random() * 30)},
        TUMBLR_SMALL: {use: Math.floor(Math.random() * 50 + 50), return: Math.floor(Math.random() * 30)},
        TUMBLR_LARGE: {use: Math.floor(Math.random() * 50 + 50), return: Math.floor(Math.random() * 30)},
        TRAY_SMALL: {use: Math.floor(Math.random() * 50 + 50), return: Math.floor(Math.random() * 30)},
        TRAY_LARGE: {use: Math.floor(Math.random() * 50 + 50), return: Math.floor(Math.random() * 30)},
        BOX_SMALL: {use: Math.floor(Math.random() * 50 + 50), return: Math.floor(Math.random() * 30)},
        BOX_MEDIUM: {use: Math.floor(Math.random() * 50 + 50), return: Math.floor(Math.random() * 30)},
        BOX_LARGE: {use: Math.floor(Math.random() * 50 + 50), return: Math.floor(Math.random() * 30)},
    },
    volume: [
        {title: '수거함 1', content: '용량: ', progress: 0},
        {title: '수거함 2', content: '용량: ', progress: 0},
        {title: '수거함 3', content: '용량: ', progress: 0},
    ],
}